### ISSUE TITLE
checksum? PGP signature?

### ISSUE THREAD

**Issue by dkliman** [stratisproject/StraxUI#18]
hi,

I want to download and use the STRAX wallet, but I cannot find the SHA256 or any other checksums for the authentic files in the readme. if you haven't yet, could you provide checksums for users' safety? even better, could you PGP sign the DMG file so I can verify it hasn't been tampered with?

**Comment by dev0tion** [comment]
Hi,

File hashes are always included on the GitHub released page: https://github.com/stratisproject/StraxUI/releases/tag/1.1.0.0

**Comment by dkliman** [comment]
Oh great! Thanks I didn’t see that. Now if only the wallet would support ledger.
