### ISSUE TITLE
Can not access the STRAX Wallet

### ISSUE THREAD

**Issue by becksari** [stratisproject/StraxUI#28]
I've tried to open the Strax Wallet (win64 type) without any success.
Loading Failed - Unable to connect to stratis node.

**Comment by dev0tion** [comment]
Hi,

This issue will be fixed in an upcoming update.
Current work around is:
- Close STRAX Wallet
- Go to %appdata%/StratisNode/Strax/StraxMain
- Remove everything except the "wallets" folder
- Start STRAX Wallet again

**Comment by becksari** [comment]
Hello all

I did what you instructed me to do.

I managed to reopen the wallet.
Unfortunately at 80% synchronization blocked again. (more than half hour
remain at 80%).

Also my funds are not visible in my account. Probably need to reach 100%
synchronization.

Any news when the new update of wallet will be released?

Regards
Teodor Amarghioalei

**Comment by hermanschutte** [comment]
Same issue for me.
