### ISSUE TITLE
Strax v1.3.0 Community Test - UI Issue - undefined

### ISSUE THREAD

**Issue by trunghieud** [stratisproject/StraxUI#60]
Send > Interflux
Check the checkbox to agree the fee and uncheck it - "undefined":

![image](https://user-images.githubusercontent.com/29716420/117323065-6bd38c00-ae43-11eb-87ad-3dbaa0f88b61.png)

Amount - "undefined" 
![image](https://user-images.githubusercontent.com/29716420/117323569-dc7aa880-ae43-11eb-8927-bb86748ab2ca.png)

Destination Address - "undefined" 
![image](https://user-images.githubusercontent.com/29716420/117323822-15b31880-ae44-11eb-807a-dfe6862e9aa1.png)

Set custom change address - "undefined"
![image](https://user-images.githubusercontent.com/29716420/117323868-21064400-ae44-11eb-811a-513aa1ffb521.png)

Send >Standard

Amount - "undefined"
![image](https://user-images.githubusercontent.com/29716420/117324485-af7ac580-ae44-11eb-923e-2c1afa7a2444.png)

Destination Address - "undefined"
![image](https://user-images.githubusercontent.com/29716420/117324314-878b6200-ae44-11eb-8a55-db46bb85492f.png)

Change address - "undefined"
![image](https://user-images.githubusercontent.com/29716420/117324401-9d008c00-ae44-11eb-9439-a212696ad85f.png)

Send > Cirrus

Amount, Sidechain destination address, Change address - "undefined"
![image](https://user-images.githubusercontent.com/29716420/117324663-d89b5600-ae44-11eb-9839-ac7609d56cf3.png)

**Comment by StratisIain** [comment]
Thanks @trunghieud - Will get this sorted.

**Comment by dev0tion** [comment]
Fixed in #66
